files = [
    'stream/taysvldlpack_male.rpf/*',
    'stream/taysvldlpack_female.rpf/*'
]

[meta]
'stream/mp_m_freemode_01_mp_m_taysvldlpack.meta' = 'SHOP_PED_APPAREL_META_FILE'
'stream/mp_f_freemode_01_mp_f_taysvldlpack.meta' = 'SHOP_PED_APPAREL_META_FILE'
'stream/pedalternatevariations.meta' = 'ALTERNATE_VARIATIONS_FILE'